In [25]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)
import math
A = np.array([[1, 2, 0],
            [0, 0, 5],
            [3, 4, 2],
            [1, 6, 5],
            [0, 1, 0]])
print(A)

[[1 2 0]
 [0 0 5]
 [3 4 2]
 [1 6 5]
 [0 1 0]]


In [26]:
U,s,W = np.linalg.svd(A)
print(U)

[[ 0.17 -0.34  0.04 -0.88 -0.28]
 [ 0.33  0.84  0.33 -0.27  0.1 ]
 [ 0.49 -0.42  0.71  0.23  0.15]
 [ 0.78 -0.01 -0.57  0.18 -0.16]
 [ 0.07 -0.13 -0.23 -0.24  0.93]]


In [3]:
V = W.T
print(V)

[[ 0.24 -0.36  0.9 ]
 [ 0.71 -0.57 -0.42]
 [ 0.66  0.74  0.12]]


In [4]:
D = np.zeros_like(A, dtype = float)
D[np.diag_indices(min(A.shape))] = s
print(D)

[[9.95 0.   0.  ]
 [0.   4.45 0.  ]
 [0.   0.   1.78]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [ 0.  0.  5.]
 [ 3.  4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


In [ ]:
#евклидова норма матрицы равна максимальному сингулярному числу 

In [33]:
print(s)#список диагональных элементов получили выше

print(f'Евклидова норма матрицы А = {s[0]:.2f}')


[9.95 4.45 1.78]
Евклидова норма матрицы А = 9.95


In [42]:
#норма фробениуса это корень из суммы квадратов всех сингулярных чисел
def my_func():
    for el in s:
        res = el**2
        print(res)
my_func()  #так выглядят квадраты

99.07295451766535
19.761865222231997
3.1651802601026273


In [36]:
print(f'Норма Фробениуса матрицы А = {math.sqrt(s[0]**2 + s[1]**2 + s[2]**2)}')



Норма Фробениуса матрицы А = 11.04536101718726
